# nginx 를 기본 이미지로 함
FROM nginx
# 작성자 정보
LABEL maintainer="cloud.ai.education@gmail.com"

# 리눅스 업데이트
RUN apt-get update

#개발과 관련한 프로그램 (파이썬등) 업데이트 -y는 설치할때 y를 자동 입력
#파이썬 3.7.3 버젼이 설치됨
RUN apt install -y software-properties-common

# 폴더 생성
# docker는 기본 이미지에 bash 대신에 sh 가 설치되 있음
# flask 프로그램을 설치할 폴더 /home/ubuntu/ai/cloud/workspace/flask_project 생성
RUN ["/bin/sh", "-c", "mkdir -p /home/ubuntu/ai/cloud/workspace/flask_project/hello_flask"]

# 파일 생성
# 현재 폴더의(./) hello_flask 폴더를 Docker container의 /home/ubuntu/ai/cloud/workspace/flask_project/hello_flask 복사
COPY ./hello_flask  /home/ubuntu/ai/cloud/workspace/flask_project/
